---
yum_repository_urls:
 - https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm

yum_packages:
 - httpd
 - php
 - mysql
 - zabbix-server-mysql
 - zabbix-web-japanese
 - zabbix-apache-conf
 - zabbix-agent2

services:
 - mysqld
 - zabbix-server
 - zabbix-agent
 - httpd

zabbix_initial_database:
  - /usr/share/doc/zabbix-server-mysql-2.2.23/create/schema.sql
  - /usr/share/doc/zabbix-server-mysql-2.2.23/create/images.sql
  - /usr/share/doc/zabbix-server-mysql-2.2.23/create/data.sql

zabbix_server_configs:
  DBHost: localhost
  DBName: zabbix
  DBUser: zabbix
  DBPassword: zabbix
  DBEncoding: utf8
  DBType: MYSQL
  DBPort: 3306
  Server: localhost
  ServerPort: 10051